### ISSUE TITLE
Set EnvironmentVariables from options

### ISSUE THREAD

**Issue by tim-cools** [pauldotknopf/JavaScriptViewEngine#11]
I would like to set some environment variables from the host ASP.NET application. I found out that JavaScriptService supports is: https://github.com/aspnet/JavaScriptServices/blob/fb19ee8923b5ef7ebb125bc6e5a1a182cfadfe88/src/Microsoft.AspNetCore.NodeServices/Configuration/NodeServicesOptions.cs#L90

Do you accept a PR that allows to set additional environment variable from NodeRenderEngineOptions?

Great project btw!

**Comment by pauldotknopf** [comment]
I'd be happy to accept a pull request!
