### ISSUE TITLE
How to debug view-related internal server error

### ISSUE THREAD

**Issue by JohnLouderback** [pauldotknopf/JavaScriptViewEngine#12]
I know the line of JS that's causing the internal server error, but I don't know why. How can I debug what's running inside the view?

I'm seeing:
![image](https://cloud.githubusercontent.com/assets/4743179/22278884/06336b52-e284-11e6-9754-493cc9d18b40.png)

The offending code is:
![image](https://cloud.githubusercontent.com/assets/4743179/22278908/22f1d2e2-e284-11e6-8f8d-1771ce57138f.png)

The problem is that I don't know why and I can't see any obvious way to trouble-shoot the problem.

EDIT: Specifically the code that runs perfectly on the client but breaks on the server view rendering is:
```typescript
new ApiClient()['get']('api/people/load').then((data) => {
  stores.people = data;
});
```
That's the code in the `loadPeople` method.

**Comment by pauldotknopf** [comment]
Checkout [this](https://github.com/pauldotknopf/JavaScriptViewEngine/blob/7b810231de3adf7cecc7b1f322653ac86760aa0a/src/JavaScriptViewEngine/NodeRenderEngineOptions.cs#L63) file.

Implement the ```ILogger``` and log the output anywhere you like. Anything that gets written to the ```stdout``` get's logged there.

**Comment by JohnLouderback** [comment]
Thanks, Paul. That helped a lot. Trying to get this working I realized I had an outdated version of the view engine as well, and that actually seems to specify a much more useful error than before. One unfortunate part is that the stack trace shows the compiled file. Is there a way to get the Node instance to use the source maps so I can find where the error is actually occurring? Troubleshooting a 2 megabyte files can be a real pain.
