### ISSUE TITLE
Missing `src/JavaScriptViewEngine.Mvc5` project

### ISSUE THREAD

**Issue by aweber1** [pauldotknopf/JavaScriptViewEngine#17]
Hi,

I pulled the latest and attempt to build using `./build.ps1` and I encounter errors from the `Build` task about a missing `JavaScriptViewEngine.Mvc5` project reference. Also attempt to load the solution in VS and the `JavaScriptViewEngine.Mvc5` project doesn't load. Looking at the path in the `.sln` file it's referencing `src/JavaScriptViewEngine.Mvc5/JavaScriptViewEngine.Mvc5.csproj`, which doesn't appear to be in the repo. Perhaps an issue with `.gitignore`?

Cheers!

**Comment by pauldotknopf** [comment]
Yup, there was a relic entry in .gitignore from old project.json stuff which caused some stuff not to be checked in. It is in there now.

Also, 1.5.0 is available, which has .NET Standard 2.
