### ISSUE TITLE
ASP.NET Core 2.0 Support?

### ISSUE THREAD

**Issue by neodescis** [pauldotknopf/JavaScriptViewEngine#18]
Are there any plans to update this library to support ASP.NET Core 2.0? I downloaded the source and it looks like all that needs to be done is to use InvokeExportAsync instead of InvokeExport in NodeRenderEngine.cs, as it was renamed in INodeServices.

**Comment by ensemblebd** [comment]
did you make a fork by chance? Would be nice to test it out and see if it works.

**Comment by pauldotknopf** [comment]
Hey guys, sorry for the delay.

This project needs to be updated to the latest bits. I have been swamped currently with other work, but I will get this done this weekend.

**Comment by pauldotknopf** [comment]
Also, I would be happy to merge any pull requests you may have :)

**Comment by ensemblebd** [comment]
hooray! thank you. Can't wait to use it on latest project in 2.0

**Comment by ensemblebd** [comment]
https://github.com/pauldotknopf/JavaScriptViewEngine/pull/19 :)

**Comment by neodescis** [comment]
Nice, thanks @ensemblebd ! Your changes are exactly what I did to get it working. I did test it out and it appears to run fine.

**Comment by pauldotknopf** [comment]
Does anybody here need the MVC5 version? I'm about to drop it.

**Comment by ensemblebd** [comment]
Not I, all good. Am trying to actively convert all systems @ job over to core, for future. 
But not sure about the other peeps. Thank you again! :)

**Comment by pauldotknopf** [comment]
The new packages are pushed to NuGet. They should be indexed soon.
