### ISSUE TITLE
Missing dll

### ISSUE THREAD

**Issue by neilyoung** [pauldotknopf/JavaScriptViewEngine#2]
Compiling JavaScriptViewEngine for .NETCoreApp,Version=v1.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:04.3719335

Expect required library hostpolicy.dll to be present in [C:\Projects\JavaScriptV
iewEngine\src\JavaScriptViewEngine\bin\Debug\netcoreapp1.0]
  - This may be because of an invalid .NET Core FX configuration in the directory.

What is wrong here?
Is this supposed to run under rc2?

**Comment by pauldotknopf** [comment]
This is an RC2 project. I'm not entirely sure what is wrong your setup. I have ran this repo on multiple machines with a clean configuration. I suspect your issue is a dotnet-cli one.

**Comment by neilyoung** [comment]
Well... checked out and run. Mac OSX, dotnet 1.0.0-preview1-002702

**Comment by pauldotknopf** [comment]
Any update on this?

**Comment by neilyoung** [comment]
You can close it. I'm no longer on this.
