### ISSUE TITLE
RuntimeBinderException coming from write async

### ISSUE THREAD

**Issue by AndrewMarkley** [pauldotknopf/JavaScriptViewEngine#3]
I'm not really sure how I got this exception but I think its happening when an empty object is passed into the enhancer at the end of configure store like this:

```
export default function configureStore(initialState, history) {
    const state = {};

    const enhancer = compose(
      applyMiddleware(thunk),
      applyMiddleware(routerMiddleware(history)),
      devTools
    )(createStore);

    return enhancer(reducers, state);
}

```

```
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: The call is ambiguous between the following methods or properties: 'System.IO.TextWriter.WriteAsync(string)' and 'System.IO.TextWriter.WriteAsync(char[])'
   at CallSite.Target(Closure , CallSite , TextWriter , Object )
   at CallSite.Target(Closure , CallSite , TextWriter , Object )
   at JavaScriptViewEngine.JsViewEngine.JsView.<RenderAsync>d__8.MoveNext()
```

It appears to be coming from one of these two lines:
https://github.com/pauldotknopf/JavaScriptViewEngine/blob/75c0027f004e5af17f41a438bc9fadf239683e8a/src/JavaScriptViewEngine/JsViewEngine.cs#L156

https://github.com/pauldotknopf/JavaScriptViewEngine/blob/75c0027f004e5af17f41a438bc9fadf239683e8a/src/JavaScriptViewEngine/JsViewEngine.cs#L160

I'll try to set up a project tonight that makes this reproducible for you since I can't share the project the error is happening in.

**Comment by pauldotknopf** [comment]
Thanks for reporting this.

Are you running from source, or from NuGet? If from NuGet, what package are you using?

**Comment by AndrewMarkley** [comment]
from nuget, version 1.2.2

**Comment by pauldotknopf** [comment]
Ah, that is out dated.

Use this NuGet package.
https://www.nuget.org/packages/JavaScriptViewEngine.MvcCore1/

The version you are using is using embedded V8. We moved away from that to a nodejs implementation.

**Comment by AndrewMarkley** [comment]
my apologies that new package didn't even come up when I searched JavaScriptViewEngine. I'll install it and try it tomorrow.

**Comment by AndrewMarkley** [comment]
@pauldotknopf Its working now. Thanks!
