### ISSUE TITLE
Adding key NODE_PATH in javascriptViewEngine

### ISSUE THREAD

**Issue by ciaosonopol** [pauldotknopf/JavaScriptViewEngine#4]
Hi Paul,
I just run the "dotnet run" command and all works fine with the boilerplate but when i run the solution with visual studio 2015 i have an issue with the "already existing NODE_PATH key", i think that can be resolved with this fix https://github.com/aspnet/JavaScriptServices/commit/a881ca5b96e1c2d8253bb1c4cd18c42e8b0a1d8e in this file JavaScriptViewEngine/src/JavaScriptViewEngine/NodeServices/HostingModels/OutOfProcessNodeInstance.cs on line 69.

I hope it help you.

Pol

**Comment by pauldotknopf** [comment]
Ah, thanks for the find. I'll get it in there when I get off of work.

Thanks!
