### ISSUE TITLE
Is it possible to specify an entry point other than wwwroot/default.js?

### ISSUE THREAD

**Issue by AustinWinstanley** [pauldotknopf/JavaScriptViewEngine#6]
Using Webpack and React. I have a `server.js` build to `wwwroot/dist/server.js` which is the one I would like to use. 

I have tried to set it like the following in configure but still get an error.

            services.Configure<RenderPoolOptions>(options => {
                options.WatchPath = Path.Combine(environment.WebRootPath, "dist");
                options.WatchFiles = new List<string> {
                    Path.Combine(options.WatchPath, "client.js"),
                    Path.Combine(options.WatchPath, "server.js")
                };
            });

The error is:

    Exception: Call to Node module failed with error: Error: Cannot find module '<repo>\wwwroot\default'

Is there a different way to set this value?

**Comment by AustinWinstanley** [comment]
A workaround that works well is to create a `default.js` and export from `dist/server.js`:

**`<repo>/wwwroot/default.js`**

    module.exports = require('./dist/server.js');

But it would still be nice to be able to set it in the config.

**Comment by pauldotknopf** [comment]
Hey @AustinWinstanley,

Your method will work.

The ```RenderPoolOptions``` is just used to configure when the pool should be reset. It doesn't configure any runtime info.

The default render engine is node, so you want to use ```NodeRenderEngineOptions``` to configure where the node directory is, and what file should be invoked.

See [this](https://github.com/pauldotknopf/react-aspnet-boilerplate/blob/d4335c2/src/ReactBoilerplate/Startup.cs#L56) line.

So, you will want something like this.

```c#
services.Configure<NodeRenderEngineOptions>(options =>
{
    options.ProjectDirectory = Path.Combine(_env.WebRootPath, "dist");
    options.GetArea = (area) =>
    {
        switch (area)
        {
            case "default":
                return "server";
            default:
                return area;
        }
    };
});
```

**Comment by AustinWinstanley** [comment]
Yep. Worked perfect. Went with shorthand but the solution worked. Thanks!

    services.Configure<NodeRenderEngineOptions>(options =>
    {
        options.ProjectDirectory = Path.Combine(environment.WebRootPath, "dist");
        options.GetArea = (area) => (area == "default") ? "server" : area;
    });
