### ISSUE TITLE
Broken/wrong link in readme for "react-aspnet-boilerplate"

### ISSUE THREAD

**Issue by EugeneKramer** [pauldotknopf/JavaScriptViewEngine#7]
The link in the readme for "react-aspnet-boilerplate" points to a dead link at:
https://github.com/pauldotknopf/JavaScriptViewEngine/blob/master/react-aspnet-boilerplate

The correct link should be:
https://github.com/pauldotknopf/react-aspnet-boilerplate

**Comment by pauldotknopf** [comment]
Thanks for noticing/reporting that, fixed!
